name: Python Parallel

on:
  push:
    branches:
      - main

jobs:
  worker:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        instance: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run script
        run: |
          python main.py ${{ matrix.instance }}
